List1 = [
    "Mon chien ",
    "Votre mère ",
    "Mes chaussettes ",
    "Le président des Etats-Unis ",
    "Le Maire ",
    "Toi ",
    "Ta tante bien aimée ",
    "Ton pays ",
    "La voiture de ton cousin ",
    "Ta tête ",
    "Ton père ",
    "Ton chapeau ",
    "Ta maison ",
    "Ton aéroglisseur ",
    "Ton mari ",
    "Ta bouilloire ",
    "Ton foie ",
    "Ta prof de math ",
    "Ton personnage préféré de jeu vidéo ",
    "Ta mère ",
    "Ton arrière train boutonné ",
    "Ton sens de la mode ",
    "Ta soeur ",
    "Tes péchés ",
    "Ton fils ",
    "Ta femme ",
    "Un seau de vomit ",
    "Un blazer pas cher ",
    "Un magasin à fromage ",
    "Une racaille alcoolique ",
    "Un friand froid ",
    "Une saucisse froide sans moutarde ",
    "Un type complètement fou ",
    "Un perroquet moutarde ",
    "Le popotin d'un démon ",
    "Un chasseur de canard ",
    "Un écolier effrayé ",
    "Une truie grognieuse ",
    "Une belle nana à moitié dévorée ",
    "Un hamster ",
    "Un petit lapin excité ",
    "Un vieux croûton paresseux ",
    "Un bûcheron ",
    "Un bouffon ",
    "Un poisson pané ",
    "Un ornithorynque ",
    "Des toilettes publiques ",
    "Un malotru ",
    "Un bon gros babouin ",
    "Un poisonnier salace ",
    "Une femme bizarre allongée sur un étang ",
    "Tous ces animaux ",
    "Un hamburger alien ",
    "Un mafieu enragé ",
    "Une porcherie ordinaire ",
    "Un poisson pourri ",
    "Un jeune homme sans défense ",
    "Des sureaux ",
    "Un steak frite ",
    "Les chaussettes d'un sans abris ",
    "Satan ",
    "Une face de thon ",
    "Un vieux débris ",
    "Un chien ",
    "Quelqu'un de fou ",
    "Cette Chose sur ton parquet ",
    "Les flics ",
    "Le sens de la vie ",
    "Cette chose que tu as eu pour ton déjeuner ",
    "Cette saleté de magasin d'animaux ",
    "Cette conversation ",
    "Ce local ",
    "Ce perroquet ",
    "Cet endroit ",
    "Ce pauvre monsieur ",
    "Ce train ",
    "La vodka ",
]

List2 = [
    "Est parti ",
    "A lavé ",
    "était ",
    "sont "
    "est appeuré par mon petit pistolet ",
    "est un vieux bougre ",
    "est un organe dans ton abdomen ",
    "est décédé","est ennuyeux et moche ",
    "se sent un peu fou ce matin ",
    "est plein d'anguilles ",
    "deviens gros ",
    "est intéréssé en photographie ",
    "se mêle ",
    "n'est plus ",
    "n'est pas intéréssant ",
    "n'est pas ma création ",
    "n'est pas sérieux ",
    "est vieux ",
    "est raciste ",
    "est plutot simple ",
    "est vulgaire ",
    "est rayé ",
    "est bête ",
    "est coupable ",
    "est une pierre morte ",
    "est très méchant ",
    "est vilain ",
    "est l'endroit ou tu t'assieds dans le train ",
    "est sans valeur ",
    "est encore un gamin ",
    "se fait bruler comme une sorcière ",
    "est en prison ",
    "a une tête disgracieuse ",
    "a mauvaise haleine","a un cancer des fesses ",
    "a aucune expérience de la vie ",
    "a aussi peu de cerveau que de cire d'oreille ",
    "a uniquement un mode multijoueur local ",
    "a des petits pieds ",
    "devrait être dans une cage ",
    "m'ennuie ",
    "rammène des insultes a un combat d'épée ",
    "peut être trouvé dans pokémon go ",
    "peut aller se faire mettre ",
    "ne peut pas acheter un escalier jusqu'au paradis ",
    "ne peut pas danser ",
    "ne tiens pas a l'alcool ",
    "ne peut pas égaliser une égalitée ",
    "n'a pas de télé en couleur ",
    "ne mange que des citrons sans gluten ",
    "a aimé Batman contre Superman ",
    "pète en ta direction ",
    "a trouvé une nouvelle application pour des fesses de chat ",
    "se déplace pour tuer des gens ",
    "se cache dans cet arbuste ",
    "aime courir avec des ciseaux ",
    "aime clignoter dans le parc ",
    "Ressemble a un maki triste ",
    "se moque du pape ",
    "me rend malade ",
    "se déplace comme une vache enceinte ",
    "doit être drôle a une soirée ",
    "a besoin d'une transplantation de foie ",
    "n'a jamais fait la fête a Moscou ",
    "n'a jamais regardé star wars ",
    "joue a cache cache ",
    "a joué a Trackmania ",
    "met des vêtements de grand-mère ",
    "aime secrètement ",
    "t'envoie ses pots et sa vaiselle la plus chaude ",
    "a signé ma pétition ",
    "utilise toujours windows vista ",
    "est nul à Overwatch ",
    "a avalé un chewing-gum ",
    "parle aux inconnus ",
    "raconte des blagues sales a un enterrement ",
    "est habitué a voler a des orphelins ",
    "vomit après avoir bu de la vodka ",
    "marche bêtement ",
    "veut des chips ",
    "porte des vêtements de seconde main ",
    "sera toujours seul ",
    "sera découpé en pièce ",
    "sera maudit pour l'éternité ",
    "est prêt à tuer pour une réservation de siège ",
    "va se réincarner en pigeon ",
    "va bientôt taper dans un seau ",
    "est autant délayé que Cyberpunk 2077 ",
    "est aussi salé qu'un joueur de League Of Legends ",
]

List3 = [
    "Ce soir ",
    "à l'école ",
    "La semaine dernière "
    "est traqué par ",
    "est né en ",
    "est vaincu par ",
    "est possédé par ",
    "a des cheuveux plus nuls que ",
    "agit comme ",
    "admire les photos de ",
    "a mangé Kevin avec ",
    "ne fait pas de sport a cause de ",
    "se change en ",
    "danse comme ",
    "est mort a cause de ",
    "n'aime pas ",
    "a donné un organe pour ",
    "bourré avec ",
    "pété sur ",
    "a fait un pari débile avec ",
    "a fait pipi sur ",
    "a surement tué ",
    "fait des nudes pour ",
    "ressemble a ",
    "s'assieds a coté de ",
    "sent comme ",
    "soutiens ",
    "a le goût de ",
    "aurait voulu être ",
    "a travaillé avec ",
    "va éventrer ",
]

List4 = [
    "car ",
    "en d'autres termes ",
    "par ailleurs ",
    "sans compter que ",
    "et ",
    "parce que ",
    "malgré ",
    "pendant ",
    "depuis ",
    "donc ",
    "ou ",
    "or ",
]

List5 = [
    "Non d'un ravioli !",
    "Mon pote/chéri !",
    "Monsieur/Madame !",
    "Et bim !"
    "Et tout le monde le sait !",
    "Et je te plains !",
    "Et je ne t'aimes pas !",
    "Et j'ai des preuves !",
    "Et je suis sérieux !",
    "Et c'est scientifiquement prouvé !",
    "Et va-t-en !",
    "Et arrête d'être un abruti !",
    "Et ce ne sont que des balivernes !",
    "Et tu ne peux pas le nier !",
    "Et tu sais que c'est vrai !",
    "Parce que je n'existe pas !"
    "Parce que tu est pourri gâté !",
    "Gros mythomane !",
    "Je parie !",
    "N'est-ce pas ?!",
    "Comme un paysan répugnant !",
    "Maintenant met une chaussette par dessus !",
    "Clin d'oeil clin d'oeil !",
    "Oh mon dieu, qui écrit ces trucs là !",
    "Ou bien est-ce à cause de ma façon de parler !",
    "Pardonne mon franglais !",
    "Dit le biscuit chinois !",
    "Donc maintenant retourne à ta place !",
    "Donc, tu sais, euh, n'est-ce pas, hein ?!",
    "Ce qui me donne des courbatures !",
    "Ce qui pourrait causer la mort !",
    "Ce qui te fera mourrir ou te rendra fou !",
    "Sale fils/fille d'ébèniste !",
    "Espèce de mauviette !",
    "Sale paysan !",
    "Pauvre mortel !",
    "Sale patate !",
    "Raclure !",
    "Malappris !",
    "Gros naze !",
    "Pignouf !",
    "Gros boloss !",
    "Espèce de moins que rien !",
    "Sale péquenaud !",
    "Tête de noeud !",
    "Triple buse !",
    "Gros tocard !",
    "Espèce de gros noob !",
    "Imbécile !",
    "Vieux schnock !",
    "Espèce d'avorton !",
]





